title: 
description: Comprehensive HTB CTF solutions for nerds and other things
baseurl: "" # Leave empty for user.github.io site
url: "https://nocturne-42.github.io"

remote_theme: jekyllt/jasper2

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

markdown: kramdown
highlighter: rouge

paginate: 100
paginate_path: "/page:num/"

author:
  name: "Me"
  bio: "CTF Player | Infosec Student | Aspiring Pentester"
  location: "Planet Earth"
